# Generated by Django 2.2 on 2019-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotmetadata',
            name='staff_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
