# Generated by Django 2.2 on 2019-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_plotmetadata_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotmetadata',
            name='data_type',
            field=models.CharField(choices=[('B', 'BASIC')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='plotmetadata',
            name='processed_data',
            field=models.FileField(upload_to='processed/'),
        ),
    ]
