# Generated by Django 2.2 on 2019-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20190414_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotmetadata',
            name='orig_raw_data_filename',
            field=models.CharField(default='non', max_length=128),
            preserve_default=False,
        ),
    ]
