# Generated by Django 2.2 on 2019-04-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_plotmetadata_orig_raw_data_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotmetadata',
            name='data_type',
            field=models.CharField(choices=[('DP', 'Demography Pie'), ('DB', 'Demography Bar')], default='DP', max_length=2),
        ),
    ]
