# Generated by Django 2.2.1 on 2019-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20190415_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fa_icon', models.CharField(max_length=20)),
            ],
        ),
    ]
