# Generated by Django 2.2.1 on 2019-05-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20190415_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotmetadata',
            name='data_type',
            field=models.CharField(choices=[('DP', 'Demography Pie'), ('DB', 'Demography Bar'), ('DS', 'Demography Stacked')], default='DP', max_length=2),
        ),
    ]
