# Generated by Django 2.2.1 on 2019-05-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content_type', models.CharField(choices=[('H', 'Title'), ('P', 'Paragram'), ('C', 'Chart')], default='H', max_length=2)),
                ('text_content', models.TextField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.PlotMetadata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Project')),
            ],
        ),
    ]
