# Generated by Django 2.2.1 on 2019-05-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='chart',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internal.PlotMetadata'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
